tap "homebrew/cask-fonts"

cask "brave-browser"
cask "google-chrome"
cask "firefox"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "beekeeper-studio"
cask "rectangle"
cask "visual-studio-code"
cask "scroll-reverser"
cask "appcleaner"
cask "unison"
cask "telegram"
cask "duplicati"
cask "docker"
cask "font-agave-nerd-font"

brew "fnm"
brew "curl"
brew "git"
brew "mosh"
brew "youtube-dl"
brew "ffmpeg"
brew "mono"
