#!/bin/bash

# adoptopenjdk is required by dbeaver
CASKS="firefox google-chrome gpg-suite-no-mail postman spotify transmission iterm2 slack dbeaver-community adoptopenjdk chromedriver bitwarden scroll-reverser 1password rectangle macs-fan-control virtualbox virtualbox-extension-pack visual-studio-code"

for CASK in $CASKS; do
  brew cask install "$CASK"
done

FORMULAE="Schniz/tap/fnm macvim curl git tree openssl htop mosh youtube-dl"

for FORMULA in $FORMULAE; do
  brew install "$FORMULA"
done

brew cleanup
