#!/bin/bash

youtube-dl \
  --add-metadata \
  --ignore-errors \
  --output "$HOME/Music/%(uploader)s/%(upload_date)s %(title)s (%(duration)ss).%(ext)s" \
  --extract-audio \
  --audio-format "mp3" \
  --audio-quality 0 \
  --download-archive "$HOME/Music/archive.txt" \
  --write-thumbnail \
  --embed-thumbnail \
  --restrict-filenames \
  $@

