#!/usr/bin/env bash

exec 3>&1 4>&2 >>"$HOME/Videos/feed-log.txt" 2>&1

download-video \
  --no-progress \
  --playlist-items 1-10 \
  --max-downloads 15 \
  --no-continue \
  --no-overwrites \
  --no-post-overwrites \
  --batch-file="$HOME/Videos/feed-list.txt" \
  --dateafter "$(date -d 'last Week' +%Y%m%d)"
