#!/bin/sh

snap refresh
snap install docker
snap install --classic code
snap install --classic aws-cli
snap install --classic postman
snap install ffmpeg
snap install spotify
snap install youtube-dl
snap install dbeaver-ce
snap install bitwarden
snap install ncdu

apt update
apt dist-upgrade -y
apt install -y \
  build-essential \
  g++ \
  gconf2 \
  dconf-editor \
  gnome-tweak-tool \
  gimp \
  gimp-plugin-registry \
  inkscape \
  aria2 \
  git \
  stow \
  tree \
  htop \
  ranger \
  gufw \
  vim-gtk \
  curl \
  wget \
  cmus \
  mpv \
  libreoffice \
  steam \
  ubuntu-restricted-extras \
  simple-scan \
  typecatcher \
  tlp \
  tlp-rdw \
  bleachbit \
  kazam \
  mosh \
  gddrescue \
  tmux \
  gnome-shell-extension-no-annoyance \
  gnome-shell-extension-disconnect-wifi \
  gnome-shell-extension-caffeine \
  gnome-shell-extension-bluetooth-quick-connect \
  gnome-shell-extension-prefs

systemctl enable tlp
tlp start

