#!/bin/bash

curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -s -- --unattended --keep-zshrc

curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash -s -- --skip-shell

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
