#!/bin/sh

CASKS="firefox google-chrome gpg-suite-no-mail postman spotify transmission vlc dropbox iterm2 slack dbeaver-community chromedriver gimp bitwarden scroll-reverser amethyst"
for CASK in $CASKS; do brew cask install "$CASK"; done

FORMULAE="wget coreutils moreutils findutils bash bash-completion git ack tree stow the_silver_searcher openssl htop ranger mosh cmus mpv youtube-dl Schniz/tap/fnm"
for FORMULA in $FORMULAE; do brew install "$FORMULA"; done

# Switch to using brew-installed bash as default shell
if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
  echo '/usr/local/bin/bash' | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/bash
fi

brew cleanup
